language: java

cache:
  directories:
  - "$HOME/.m2/repository"

services:
  - docker

script:
  - mvn clean verify
  - docker build -t sample-application-db-changelog-job ./sample-application-db-changelog-job
  - docker build -t sample-application-http-api-server ./sample-application-http-api-server

deploy:
  provider: script
  script:
      - echo "$PASSWORD_DOCKER" | docker login -u "$USERNAME_DOCKER" --password-stdin
      - docker build -t sample-application-students .
      - docker images
      - docker tag sample-application-students $DOCKER_USERNAME/sample-application-students
      - docker push $DOCKER_USERNAME/sample-application-students
  on:
    branch: develop
